### ISSUE TITLE
TLS SNI support

### ISSUE THREAD

**Issue by dweinstein** [alibaba/anyproxy#14]
I don't think that currently [SNI](http://en.m.wikipedia.org/wiki/Server_Name_Indication) is supported.

**Comment by dweinstein** [comment]
See how mitmproxy supports this complication [here](https://github.com/mitmproxy/mitmproxy/blob/master/doc-src/howmitmproxy.html#L125)

**Comment by ottomao** [comment]
I've read the wiki about SNI, but can not fully understand it.
In AnyProxy, certificates are signed with hostname, not ip address. So there shouldn't be any problem with virtual hosts.

**Comment by dweinstein** [comment]
Please see the list of complications mitmproxy talks about here: https://github.com/mitmproxy/mitmproxy/blob/master/doc-src/howmitmproxy.html#L125

They are hopefully documented a little better than the wiki page and can help clarify the different scenarios rather than me restating it :-)

**Comment by guangwong** [comment]
按理说支持了 SNI 你现在的模式就不用监听那么多端口了。 其实还有更好的解决方案 XD （我已经在 0.11.x 的 Node 上实现了更好方案，还没有去支持 0.10.x，不过代码在内网 ）。

**Comment by ottomao** [comment]
@dweinstein 
Perhaps I've found out why SNI is not necessary our proxy server.
For regular https servers,  users send requests DIRECTLY to it. So a server should identify the hostname  during TLS handshaking(OSI layer 5) and deliver a corresponding certificate. This is why SNI should be invoked on virtual hosts.

When it comes to proxy server, something changed. If a user wants to connect an https server via proxy, the browser will send an http(not https) request with CONNECT method first. During this process, the proxy server could learn the target host name and then establish a socket tunnel to target server. Now you can see, since we have got the hostname on OSI layer 7, SNI is no longer needed.

Please note that we are talking about regular proxy server, not reverse proxy for load balance on server side.

**Comment by ottomao** [comment]
@dweinstein 
The previous comment explains why SNI is not needed in the user-side interface of proxy. 
After thinking it again, maybe it is still necessary for the back-side. When the target server is deployed on a virtual host, we have to implement SNI on proxy side correspondingly. 
The solution may have to do with something about nodejs api. I'll try to find out and publish a new version if needed.

Thanks !

**Comment by ottomao** [comment]
@guangwong 如上文所述，SNI应该是Proxy向server发送信息时需要支持的特性。至于用户这边的方案，多开几个端口也没什么问题，哈哈。

**Comment by guangwong** [comment]
@ottomao 是呀，单机自己用这样也是没有关系的。 我在做淘宝这边的一个集中代理工具，是集中式的需要多考虑这些的（最伤心的还有证书安全。。 ）。

**Comment by ottomao** [comment]
@guangwong 不知道有没有给你回复过，AnyProxy现在已经支持SNI了，不用再开这么多端口。

**Comment by guangwong** [comment]
@ottomao 好的~  我这才知道

**Comment by Degreane** [comment]
嗨，大家好。
是否有任何教程如何运行anyproxy SNI支持（和TLS），如果可能的话？
也将是非常容易的，如果它可以透明地运行。

而且我一定在客户端浏览器包括证书或工作的透明？

很多问候

**Comment by ottomao** [comment]
@Degreane  
Did you use online translation service to get these Chinese words ? It's hard to understand. :(

**Comment by Degreane** [comment]
Yes sorry ;) 
anyhow was asking if there are any tutorials on how to run anyproxy SNI support (and TLS), if possible?
It will also be very useful if it can run transparently without adding manually the certificate to client browsers. or to find a way to push it to the client browser.

much regards

**Comment by codingfishman** [comment]
AnyProxy is now support SNI, close the issue.
